architectury {
    fabric()
}

configurations {
    developmentFabric.extendsFrom common
}

loom {
    runs {
        data {
            inherit client

            name 'Data Generation'

            vmArg '-Dfabric-api.datagen'
            vmArg "-Dfabric-api.datagen.output-dir=${file("../src/generated/resources")}"
            vmArg '-Dfabric-api.datagen.modid=catsplus'

            runDir 'run/datagen'
        }
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    modApi "games.moegirl.sinocraft:sinocore-fabric:${rootProject.sinocore_version}"

    modRuntimeOnly "com.terraformersmc:modmenu:${rootProject.fabric_mod_menu_version}"
    modRuntimeOnly "cx.rain.mc.nbtedit:nbtedit-fabric:${rootProject.runtime_nbtedit_version}"

    shadowBundle project(path: ':', configuration: 'transformProductionFabric')
}

remapJar {
    injectAccessWidener = true
}
