modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/CuteNekoOwO/CatsPlus/issues"

[[mods]]
modId = "catsplus"
version = "${mod_version}"
displayName = "Cats+"
displayURL = "https://github.com/CuteNekoOwO/CatsPlus"
logoFile = "logo.png"
credits = "YukieMiona, Kogasa-Studio"
authors = "MeowBot233, CuteNekoOwO and qyl27"
displayTest = "MATCH_VERSION"
description = '''
Make cats in Minecraft more fun!
'''

[[dependencies.catsplus]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.catsplus]]
modId = "minecraft"
mandatory = true
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.catsplus]]
modId = "sinocore"
mandatory = true
versionRange = "${neoforge_sinocore_version_range}"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "catsplus-common.mixins.json"
